import type { Event } from "./types"

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    name: "Annual Gala Dinner (Sample table placement event)",
    type: "Gala",
    status: "Upcoming",
    description: "Join us for an elegant evening of dinner, entertainment, and fundraising...",
    startDate: "2024-03-15",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    venue: "Grand Ballroom, Civic Center",
    address: "123 Main Street",
    city: "Springfield",
    state: "IL",
    postalCode: "62701",
    capacity: 300,
    ticketPrice: 250.0,
    fundraisingGoal: 150000,
    registered: 245,
    revenue: 122500,
    tags: ["gala", "upcoming"],
  },
  {
    id: "evt-2",
    name: "Spring Charity Auction (Sample seating event)",
    type: "Auction",
    status: "Upcoming",
    description: "Bid on exclusive items and experiences to support our mission...",
    startDate: "2024-04-20",
    startTime: "5:30 PM",
    endTime: "9:00 PM",
    venue: "Heritage Museum",
    address: "456 Oak Avenue",
    city: "Springfield",
    state: "IL",
    postalCode: "62702",
    capacity: 200,
    ticketPrice: 375.0,
    fundraisingGoal: 75000,
    registered: 167,
    revenue: 45000,
    tags: ["auction", "upcoming"],
  },
  {
    id: "evt-3",
    name: "Community 5K Run/Walk",
    type: "Fundraiser",
    status: "Upcoming",
    description: "Get active and support a great cause with our annual 5K event...",
    startDate: "2024-05-10",
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    venue: "Riverside Park",
    address: "789 Park Lane",
    city: "Springfield",
    state: "IL",
    postalCode: "62703",
    capacity: 500,
    ticketPrice: 50.0,
    fundraisingGoal: 25000,
    registered: 342,
    revenue: 17100,
    tags: ["fundraiser", "upcoming"],
  },
  {
    id: "evt-4",
    name: "Donor Appreciation Lunch",
    type: "Stewardship",
    status: "Ongoing",
    description: "A special thank you event for our valued donors and supporters...",
    startDate: "2024-02-28",
    startTime: "12:00 PM",
    endTime: "2:00 PM",
    venue: "Harborview Restaurant",
    address: "321 Harbor Drive",
    city: "Springfield",
    state: "IL",
    postalCode: "62704",
    capacity: 75,
    ticketPrice: 0,
    fundraisingGoal: 0,
    registered: 68,
    revenue: 0,
    tags: ["stewardship", "ongoing"],
  },
  {
    id: "evt-5",
    name: "Grant Writing Workshop",
    type: "Workshop",
    status: "Upcoming",
    description: "Learn the fundamentals of grant writing from industry experts...",
    startDate: "2024-03-05",
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    venue: "Community Center Room B",
    address: "555 Community Blvd",
    city: "Springfield",
    state: "IL",
    postalCode: "62705",
    capacity: 40,
    ticketPrice: 0,
    fundraisingGoal: 0,
    registered: 35,
    revenue: 0,
    tags: ["workshop", "upcoming"],
  },
  {
    id: "evt-6",
    name: "Holiday Fundraiser 2023",
    type: "Fundraiser",
    status: "Completed",
    description: "Celebrate the season while supporting our year-end campaign...",
    startDate: "2023-12-10",
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    venue: "Celebration Hall",
    address: "999 Festival Way",
    city: "Springfield",
    state: "IL",
    postalCode: "62706",
    capacity: 250,
    ticketPrice: 350.0,
    fundraisingGoal: 75000,
    registered: 250,
    revenue: 87500,
    tags: ["fundraiser", "completed"],
  },
]
