import type { TimelineItem } from "../types"

export const mockTimelineItems: TimelineItem[] = [
  {
    id: "1",
    type: "pinned-note",
    title: "PINNED NOTE",
    description: "Major donor prospect - previous $500K gift in 2022. Interested in naming opportunities for new science building.",
    addedBy: "Maria Garcia",
    date: "November 4, 2024 at 4:20 PM",
  },
  {
    id: "2",
    type: "pinned-note",
    title: "PINNED NOTE",
    description: "Prefers email communication. Best time to reach is weekday mornings 9-11am.",
    addedBy: "Sarah Johnson",
    date: "October 14, 2024 at 10:00 AM",
  },
  {
    id: "3",
    type: "overdue-task",
    title: "OVERDUE TASK",
    description: "Schedule site visit for grant review",
    dueDate: "October 17, 2024 at 10:00 AM",
    owner: "Alex Russo",
    date: "",
  },
  {
    id: "4",
    type: "overdue-task",
    title: "OVERDUE TASK",
    description: "Thank you call for recent donation",
    dueDate: "October 24, 2024 at 3:30 PM",
    owner: "Maria Garcia",
    date: "",
  },
  {
    id: "5",
    type: "open-task",
    title: "TASK: OPEN",
    description: "Follow up on capital campaign discussion",
    createdDate: "November 10, 2025 at 10:30 AM",
    dueDate: "November 14, 2025 at 2:00 PM",
    owner: "Maria Garcia",
    date: "",
  },
  {
    id: "6",
    type: "gift",
    title: "GIFT",
    amount: "$500",
    fund: "General Fund",
    channel: "Organic",
    giftType: "Credit Card",
    campaign: "Direct Mail 2025 - Housefile (Moore Group)",
    notes: "Monthly recurring gift",
    date: "November 10, 2025",
    addedBy: "2:32 PM",
  },
  {
    id: "7",
    type: "ask",
    title: "ASK",
    amount: "$15,000",
    status: "Pending",
    description: "Capital Campaign - Building Expansion",
    followUp: "December 10, 2025",
    notes: "Very positive conversation, considering pledge over 3 years",
    addedBy: "Maria Garcia",
    date: "November 10, 2025",
    createdDate: "2:00 PM",
  },
  {
    id: "8",
    type: "pledge",
    title: "PLEDGE",
    amount: "$15,000",
    status: "Active",
    fund: "Capital Campaign",
    installments: "3 (Annual)",
    balance: "$10,000",
    nextPayment: "December 10, 2025",
    notes: "Pledge for building expansion, 3 annual payments of $5,000",
    addedBy: "Maria Garcia",
    date: "November 10, 2025",
    createdDate: "9:00 AM",
  },
  {
    id: "9",
    type: "contact-info-generated",
    title: "CONTACT INFORMATION GENERATED",
    description: "Email: jennifer.lee@techcorp.com, Phone: (555) 123-4567, Address: 123 Main St, San Francisco, CA 94102",
    addedBy: "Sapling AI",
    date: "November 10, 2025 at 11:30 AM",
  },
  {
    id: "10",
    type: "wealth-info-generated",
    title: "WEALTH INFORMATION GENERATED",
    description: "Estimated Capacity: $100K-$250K, Real Estate Value: $1.2M, Business Affiliations: Tech Executive, Wealth Rating: High",
    addedBy: "Sapling AI",
    date: "November 10, 2025 at 11:45 AM",
  },
  {
    id: "11",
    type: "workflow-change",
    title: "ORCHID AI WORKFLOW CHANGE",
    description: 'Workflow "Major Donor Stewardship" changed from "Initial Outreach" to "Cultivation Meeting Scheduled". Next action: Schedule in-person meeting within 2 weeks.',
    addedBy: "Orchid AI",
    date: "November 10, 2025 at 12:00 PM",
  },
  {
    id: "12",
    type: "data-enrichment",
    title: "DATA ENRICHMENT",
    description: "Wealth screening, contact info, and social profiles updated",
    addedBy: "Sapling System",
    date: "November 10, 2025 at 10:15 PM",
  },
  {
    id: "13",
    type: "document",
    title: "DOCUMENT",
    documentType: "Gift Agreement",
    fileName: "Capital Campaign Gift Agreement 2024.pdf",
    description: "Signed gift agreement for $15,000 capital campaign pledge",
    notes: "Three-year commitment with annual payments",
    addedBy: "Maria Garcia",
    date: "November 10, 2025 at 10:00 AM",
  },
  {
    id: "14",
    type: "legacy-giving",
    title: "LEGACY GIVING",
    intentType: "Bequest Intent",
    documented: true,
    estimated: "$100,000",
    description: "Jennifer expressed interest in including organization in estate plans. Sent legacy society information.",
    notes: "Follow up in December to discuss specific bequest language",
    addedBy: "Maria Garcia",
    date: "November 10, 2025 at 2:00 PM",
  },
  {
    id: "15",
    type: "event",
    title: "EVENT",
    eventName: "Annual Gala 2024",
    status: "Attended",
    description: "Jennifer attended with guest, very engaged with other donors",
    ticket: "$250",
    table: "5",
    guests: "2",
    notes: "Expressed interest in sponsoring next year",
    addedBy: "Maria Garcia",
    date: "November 10, 2025 at 6:00 PM",
  },
  {
    id: "16",
    type: "fulfillment",
    title: "FULFILLMENT",
    documentType: "Thank You Gift",
    itemName: "Engraved crystal paperweight",
    description: "Acknowledgement gift for capital campaign pledge",
    carrier: "UPS",
    tracking: "UPS123456789",
    notes: "Delivered successfully, personalized with donor name",
    addedBy: "Maria Garcia",
    date: "November 10, 2025 at 10:00 AM",
  },
  {
    id: "17",
    type: "membership",
    title: "MEMBERSHIP",
    status: "Active",
    description: "Sample Charity Recurring Club",
    membershipAmount: "$50/monthly",
    renewal: "Monthly",
    notes: "New monthly recurring membership",
    addedBy: "Maria Garcia",
    date: "November 10, 2025 at 10:00 AM",
  },
  {
    id: "18",
    type: "call-note",
    title: "Call",
    description: "Follow-up on Capital Campaign",
    notes: "Called Jennifer to discuss her potential participation in the capital campaign. She expressed interest in learning more about the building expansion.",
    outcome: "Positive",
    nextSteps: "Send detailed campaign materials and schedule in-person meeting",
    addedBy: "Maria Garcia added a note",
    date: "November 9, 2025",
    createdDate: "10:30",
  },
]
