import {
  Pin,
  AlertCircle,
  CheckSquare,
  Gift,
  DollarSign,
  TrendingUp,
  Sparkles,
  Zap,
  FileText,
  Heart,
  Calendar,
  Send,
  Users,
  Phone,
} from "lucide-react"
import type { TimelineItemStyles, TimelineItemType } from "../types"

export const timelineStyles: Record<TimelineItemType, TimelineItemStyles> = {
  "pinned-note": {
    borderColor: "border-l-amber-400",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    badgeColor: "bg-amber-100 text-amber-700",
    Icon: Pin,
  },
  "overdue-task": {
    borderColor: "border-l-red-400",
    bgColor: "bg-red-50",
    iconBg: "bg-red-100",
    iconColor: "text-red-600",
    badgeColor: "bg-red-100 text-red-700",
    Icon: AlertCircle,
  },
  "open-task": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/10",
    iconBg: "bg-sapling-light/20",
    iconColor: "text-sapling",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: CheckSquare,
  },
  "gift": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-white",
    iconBg: "bg-sapling-light",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: Gift,
  },
  "ask": {
    borderColor: "border-l-amber-400",
    bgColor: "bg-amber-50",
    iconBg: "bg-amber-500",
    iconColor: "text-white",
    badgeColor: "bg-amber-100 text-amber-700",
    Icon: DollarSign,
  },
  "pledge": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/5",
    iconBg: "bg-sapling-light",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: TrendingUp,
  },
  "contact-info-generated": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/10",
    iconBg: "bg-sapling-light",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: Sparkles,
  },
  "wealth-info-generated": {
    borderColor: "border-l-purple-400",
    bgColor: "bg-purple-50",
    iconBg: "bg-purple-500",
    iconColor: "text-white",
    badgeColor: "bg-purple-100 text-purple-700",
    Icon: Sparkles,
  },
  "workflow-change": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/5",
    iconBg: "bg-amber-500",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: Zap,
  },
  "data-enrichment": {
    borderColor: "border-l-orange-400",
    bgColor: "bg-orange-50",
    iconBg: "bg-purple-500",
    iconColor: "text-white",
    badgeColor: "bg-orange-100 text-orange-700",
    Icon: Sparkles,
  },
  "document": {
    borderColor: "border-l-gray-400",
    bgColor: "bg-white",
    iconBg: "bg-gray-200",
    iconColor: "text-gray-600",
    badgeColor: "bg-gray-100 text-gray-700",
    Icon: FileText,
  },
  "legacy-giving": {
    borderColor: "border-l-pink-400",
    bgColor: "bg-pink-50",
    iconBg: "bg-pink-500",
    iconColor: "text-white",
    badgeColor: "bg-pink-100 text-pink-700",
    Icon: Heart,
  },
  "event": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/5",
    iconBg: "bg-amber-500",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: Calendar,
  },
  "fulfillment": {
    borderColor: "border-l-purple-400",
    bgColor: "bg-purple-50",
    iconBg: "bg-purple-500",
    iconColor: "text-white",
    badgeColor: "bg-purple-100 text-purple-700",
    Icon: Send,
  },
  "membership": {
    borderColor: "border-l-sapling-light",
    bgColor: "bg-sapling-light/5",
    iconBg: "bg-amber-500",
    iconColor: "text-white",
    badgeColor: "bg-sapling-light/20 text-sapling",
    Icon: Users,
  },
  "call-note": {
    borderColor: "border-l-gray-300",
    bgColor: "bg-white",
    iconBg: "bg-gray-100",
    iconColor: "text-gray-600",
    badgeColor: "bg-gray-100 text-gray-700",
    Icon: Phone,
  },
}
